version: '2'
services:
  apache:
    image: rafaelcgstz/magento2
    # build: .
    ports:
      - "80:80" # web
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - magento-sources-sync:/var/www/html:nocopy
#      - ~/.composer:/var/www/.composer
#      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.88.207"
      PHP_IDE_CONFIG: "serverName=dockerized-magento2.local"
    depends_on:
      - db
    links:
      - db
    networks:
      - magento2-network

  db:
    image: mysql:latest
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - magento2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - magento2-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento2-network

networks:
  magento2-network:
    driver: bridge

volumes:
  magento-sources-sync:
    external: true
  dbdata:
    driver: local
